<?php
require_once "../../../controllers/employees.controller.php";
require_once "../../../models/employees.model.php";

require_once "../../../controllers/products.controller.php";
require_once "../../../models/products.model.php";

require_once "../../../controllers/inventory.controller.php";
require_once "../../../models/inventory.model.php";

class printInventorySheet{

public $refcode;
public function getTallyInventoryPrinting(){
  $itemRefcode = "refcode";
  $refcode = $this->refcode;

  $inventory = (new ControllerInventory)->ctrShowInventoryInfo($itemRefcode, $refcode);
  $id = $inventory['id'];
  $refcode = $inventory['refcode'];
  $tdate = $inventory['tdate'];
  $remarks = $inventory['remarks'];
  $idEmployee = $inventory['idEmployee']; 
  $trans_date = substr($tdate,5,2)."/".substr($tdate,8,2)."/".substr($tdate,0,4);
  // $productlist = json_decode($inventory['productlist'], true);

  $itemEmployee = "id";
  $valueEmployee = $idEmployee;
  $answerEmployee = (new ControllerEmployees)->ctrShowEmployees($itemEmployee, $valueEmployee);
  $prepared_by = $answerEmployee['fname'].' '.$answerEmployee['lname']; 

  $productlist = (new ControllerInventory)->ctrShowPhysicalInventory($refcode);

  require_once('tcpdf_include.php');
  $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
  $pdf->startPageGroup();
  $pdf->setPrintHeader(false);	/*remove line on top of the page*/
  $pdf->AddPage();

  $header = <<<EOF
    <table>
      <tr>
        <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">RIVSON COMMERCIAL WAREHOUSE</td> 
      </tr>

      <tr>
        <td style="width:540px;text-align:center;font-size:10px;">Sharina Hts., Brgy. Taculing, Bacolod City</td> 
      </tr>  

      <tr>
        <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">Physical Inventory</td> 
      </tr>

      <tr>
        <td style="width:449px;text-align:right;font-size:11px;">PI # :</td>
        <td style="width:65px;text-align:left;font-size:11px;">&nbsp;$refcode</td>                
      </tr>

      <tr>
        <td style="width:449px;text-align:right;font-size:11px;">Date :</td>
        <td style="width:65px;text-align:left;font-size:11px;">&nbsp;$trans_date</td>                
      </tr>    
 
      <tr>
        <td style="width:25px;"></td>

        <td style="border: 1px solid #666;width:150px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;Category</td>        

        <td style="border: 1px solid #666;width:255px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;Product(s)</td>
                                                            
        <td style="border: 1px solid #680;width:75px;text-align:right;font-size:11px;">Qty &nbsp;&nbsp;&nbsp;</td>               
      </tr>                  
    </table>
EOF;
  $pdf->writeHTML($header, false, false, false, false, '');

// ------------------------------------------------------------  
$i = 0;  
$curr_desc = '';
$prev_catname = '';
foreach ($productlist as $key => $value) {
  $i = $i + 1;
  $catname = $value["catname"];
  $pdesc = $value["pdesc"];

  if ($pdesc == null){
    $pdesc = '';
    $catname = '';
  }else{
    if ($i == 1){
      $prev_catname = $catname;
    }else{
      $curr_desc = $catname;
      if ($prev_catname == $curr_desc){
        $catname = '';
      }
      $prev_catname = $curr_desc;
    }                 
  }
  $qty = number_format($value["qty"]);

  if ($value["pdesc"] == null){
  $subtotal = <<<EOF
    <table style="border: none;">    
      <tr>
        <td style="width:25px;"></td>

        <td style="width:150px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;$catname</td>        

        <td style="width:287px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;$pdesc</td>

        <td style="width:48px;text-align:right;font-size:11px;border-top: 1px solid black;font-weight:bold;">$qty &nbsp;&nbsp;&nbsp;</td>
      </tr>         
      <tr>
        <td></td>
      </tr>        
    </table>
EOF;
  $pdf->writeHTML($subtotal, false, false, false, false, '');
  }else{
  $content = <<<EOF
    <table style="border: none;">    
      <tr>
        <td style="width:25px;"></td>

        <td style="width:150px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;$catname</td>        

        <td style="width:287px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;$pdesc</td>

        <td style="width:48px;text-align:right;font-size:11px;">$qty &nbsp;&nbsp;&nbsp;</td>
      </tr>                 
    </table>
EOF;
  $pdf->writeHTML($content, false, false, false, false, '');    
  }
}

  $footer = <<<EOF
    <table style="border: none;">    
      <tr>
        <td></td>
      </tr>
      <tr>  
        <td style="width:505px;text-align:right;font-size:8px;">Generated by</td>
      </tr> 
      <tr>  
        <td style="width:505px;text-align:right;font-size:10px;">$prepared_by</td>
      </tr>                              
    </table>
EOF;
  $pdf->writeHTML($footer, false, false, false, false, '');  

  $pdf->Output('inventoryprint.pdf', 'I');
 }
}

$inventoryForm = new printInventorySheet();
$inventoryForm -> refcode = $_GET["refcode"];
$inventoryForm -> getTallyInventoryPrinting();
?>