<?php
session_start();

require_once "../../../controllers/rawmaterials.controller.php";
require_once "../../../models/rawmaterials.model.php";

require_once "../../../controllers/employees.controller.php";
require_once "../../../models/employees.model.php";

class printRawListPriceTemplate{

public function getRawListTemplatePricePrinting(){
  $id = "id";
  $empid = $_SESSION["idEmployee"];
  $employee = (new ControllerEmployees)->ctrShowEmployees($id, $empid);
  $generated_by = $employee['fname'].' '.$employee['lname']; 

  $materials = (new controllerMaterials)->ctrShowPriceTrail();

  require_once('tcpdf_include.php');
  $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
  $pdf->startPageGroup();
  $pdf->setPrintHeader(false);	/*remove line on top of the page*/

  // $pdf->AddPage();   /*short-size portrait*/
  $pdf->AddPage('L', 'LETTER');
  $header = <<<EOF
    <table>
      <tr>
        <td style="width:536px;text-align:center;font-size:1.2em;font-weight:bold;">RIVSON GOLDPLAST MANUFACTURING CORPORATION</td> 
      </tr>

      <tr>
        <td style="width:536px;text-align:center;font-size:10px;">Purok Paho, Brgy. Felisa, Bacolod City</td> 
      </tr>  

      <tr>
        <td style="width:536px;text-align:center;font-size:1.2em;font-weight:bold;">RAW MATERIALS PRICE TRAIL</td> 
      </tr>   

      <tr>
        <td></td>
      </tr>

      <tr>
        <td style="width:5px;"></td>

        <td style="border: 1px solid #666;width:70px;text-align:left;font-size:10px;">&nbsp;&nbsp;&nbsp;Category</td>
                                                            
        <td style="border: 1px solid #680;width:282px;text-align:left;font-size:10px;">&nbsp;&nbsp;&nbsp; Description </td>    

        <td style="border: 1px solid #680;width:60px;text-align:right;font-size:10px;">Date &nbsp;</td>   

        <td style="border: 1px solid #680;width:195px;text-align:left;font-size:10px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Supplier </td>                     

        <td style="border: 1px solid #680;width:60px;text-align:right;font-size:10px;">Price &nbsp;</td>     

        <td style="border: 1px solid #666;width:45px;text-align:left;font-size:10px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Meas</td>                  
      </tr>                   
    </table>
EOF;
    $pdf->writeHTML($header, false, false, false, false, '');

// ------------------------------------------------------------
  $prev_desc = '';
  $prev_price = 0.00;  
  foreach ($materials as $key => $value) {
    $cdesc = $value["cdesc"];
    $rawmat = $value["rawmat"];
    $measmat = $value["measmat"];
    $ucost = $value["ucost"];
    $sname = $value["sname"];
    $deldate = $value["deldate"];
    $del_date = substr($deldate,5,2)."/".substr($deldate,8,2)."/".substr($deldate,0,4);

    if (($prev_desc != $rawmat)||($prev_price != $ucost)){
        if ($prev_desc == $rawmat){
          $rawmat = '';
          $cdesc = '';
        }

    $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:5px;"></td>

          <td style="width:70px;text-align:left;font-size:10px;">&nbsp;&nbsp;&nbsp;$cdesc</td>
                                                              
          <td style="width:282px;text-align:left;font-size:9px;">&nbsp;&nbsp;&nbsp; $rawmat</td>       

          <td style="width:66px;text-align:right;font-size:10px;">$del_date &nbsp;</td>  

          <td style="width:195px;text-align:left;font-size:9px;">&nbsp;&nbsp;&nbsp; $sname</td>            

          <td style="width:66px;text-align:right;font-size:10px;">$ucost &nbsp;&nbsp;&nbsp;&nbsp;</td>                             

          <td style="width:45px;text-align:left;font-size:10px;">&nbsp;&nbsp;&nbsp;$measmat</td>           
        </tr>                 
      </table>
EOF;
      $pdf->writeHTML($content, false, false, false, false, '');

      $prev_desc = $value["rawmat"];
      $prev_price = $ucost;
    }   
  }  /*for*/      

  $footer = <<<EOF
    <table style="border: none;">    
      <tr>
        <td></td>
      </tr>
      <tr>  
        <td style="width:715px;text-align:right;font-size:8px;">Generated by</td>
      </tr> 
      <tr>  
        <td style="width:715px;text-align:right;font-size:10px;">$generated_by</td>
      </tr>                              
    </table>
EOF;
      $pdf->writeHTML($footer, false, false, false, false, '');

    $pdf->Output('rawmaterials_list.pdf', 'I');
   }
  }  

  $materialsPriceListForm = new printRawListPriceTemplate();
  $materialsPriceListForm -> getRawListTemplatePricePrinting();
?>