<?php
session_start();

require_once "../../../controllers/rawmaterials.controller.php";
require_once "../../../models/rawmaterials.model.php";

require_once "../../../controllers/employees.controller.php";
require_once "../../../models/employees.model.php";

class printRawListTemplate{

public function getRawListTemplatePrinting(){
  $id = "id";
  $empid = $_SESSION["idEmployee"];
  $employee = (new ControllerEmployees)->ctrShowEmployees($id, $empid);
  $generated_by = $employee['fname'].' '.$employee['lname']; 

  $materials = (new controllerMaterials)->ctrShowMaterialsList();

  // Date Label
  $inventory_label_date = 'Date: ____________';

  require_once('tcpdf_include.php');
  $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
  $pdf->startPageGroup();
  $pdf->setPrintHeader(false);	/*remove line on top of the page*/

  // $pdf->AddPage();   /*short-size portrait*/
  $pdf->AddPage('L', 'LETTER');
  $header = <<<EOF
    <table>
      <tr>
        <td style="width:704px;text-align:center;font-size:1.2em;font-weight:bold;">RIVSON GOLDPLAST MANUFACTURING CORPORATION</td> 
      </tr>

      <tr>
        <td style="width:704px;text-align:center;font-size:10px;">Purok Paho, Brgy. Felisa, Bacolod City</td> 
      </tr>  

      <tr>
        <td style="width:704px;text-align:center;font-size:1.2em;font-weight:bold;">PRODUCTS INVENTORY TEMPLATE</td> 
      </tr>   

      <tr>
        <td></td>
      </tr>

      <tr>
        <td style="width:495px;"></td>
        <td style="width:210px;text-align:right;font-size:11px;">$inventory_label_date</td>
      </tr>

      <tr>
        <td style="width:20px;"></td>

        <td style="border: 1px solid #666;width:102px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;Category</td>
                                                            
        <td style="border: 1px solid #680;width:252px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp; Description </td>

        <td style="border: 1px solid #680;width:215px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp; Details </td>        

        <td style="border: 1px solid #680;width:70px;text-align:right;font-size:11px;">Count &nbsp;&nbsp;&nbsp;</td>     

        <td style="border: 1px solid #666;width:45px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;Meas</td>                  
      </tr>                   
    </table>
EOF;
    $pdf->writeHTML($header, false, false, false, false, '');

// ------------------------------------------------------------
  foreach ($materials as $key => $value) {
    $cdesc = $value["cdesc"];
    $rawmat = $value["rawmat"];
    $measmat = $value["measmat"];
    $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:20px;"></td>

          <td style="width:102px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;$cdesc</td>
                                                              
          <td style="width:252px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp; $rawmat</td>

          <td style="width:215px;text-align:left;font-size:11px;">__________________________________</td>          

          <td style="width:77px;text-align:right;font-size:11px;">________ &nbsp;&nbsp;&nbsp;</td>  

          <td style="width:45px;text-align:left;font-size:11px;">&nbsp;&nbsp;&nbsp;$measmat</td>           
        </tr>                 
      </table>
EOF;
      $pdf->writeHTML($content, false, false, false, false, ''); 
  }  /*for*/      

  $footer = <<<EOF
    <table style="border: none;">    
      <tr>
        <td></td>
      </tr>
      <tr>  
        <td style="width:700px;text-align:right;font-size:8px;">Generated by</td>
      </tr> 
      <tr>  
        <td style="width:700px;text-align:right;font-size:10px;">$generated_by</td>
      </tr>                              
    </table>
EOF;
      $pdf->writeHTML($footer, false, false, false, false, '');

    $pdf->Output('rawmaterials_list.pdf', 'I');
   }
  }  

  $materialsListForm = new printRawListTemplate();
  $materialsListForm -> getRawListTemplatePrinting();
?>